[package]
name = "schegen"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }

[dev-dependencies]
assert_cmd = "2.0"
predicates = "2.1"
log = "0.4"
env_logger = "0.11.6"
schematools = "0.19.2"
anyhow = "1.0"
tempfile = "3.8"
